from jacobinet.layers.convolutional import (
    BackwardConv1D,
    BackwardConv2D,
    BackwardConv3D,
    BackwardDepthwiseConv1D,
    BackwardDepthwiseConv2D,
)
from jacobinet.layers.core import BackwardActivation, BackwardDense, BackwardEinsumDense
from jacobinet.layers.custom import (
    BackwardAbs,
    get_backward_Abs,
    get_backward_Absolute,
    get_backward_AMax,
    get_backward_AMin,
    get_backward_Arccos,
    get_backward_Arccosh,
    get_backward_Arcsin,
    get_backward_Arcsinh,
    get_backward_Arctan,
    get_backward_Arctanh,
    get_backward_Average,
    get_backward_Cos,
    get_backward_Cosh,
    get_backward_CumProd,
    get_backward_Cumsum,
    get_backward_Diagonal,
    get_backward_ExpandDims,
    get_backward_Expm1,
    get_backward_Floor,
    get_backward_FullLike,
    get_backward_Log,
    get_backward_Log1p,
    get_backward_Log2,
    get_backward_Log10,
    get_backward_MoveAxis,
    get_backward_Negative,
    get_backward_Norm,
    get_backward_OnesLike,
    get_backward_Prod,
    get_backward_Reciprocal,
    get_backward_Repeat,
    get_backward_Roll,
    get_backward_Sign,
    get_backward_Sin,
    get_backward_Sinh,
    get_backward_Sort,
    get_backward_Sqrt,
    get_backward_Square,
    get_backward_SwapAxes,
    get_backward_Tan,
    get_backward_Trace,
    get_backward_Transpose,
    get_backward_Tril,
    get_backward_Triu,
    get_backward_Trunc,
    get_backward_Var,
    get_backward_ZerosLike,
)
from jacobinet.layers.normalization import BackwardBatchNormalization
from jacobinet.layers.pooling import (
    BackwardAveragePooling1D,
    BackwardAveragePooling2D,
    BackwardAveragePooling3D,
    BackwardGlobalAveragePooling1D,
    BackwardGlobalAveragePooling2D,
    BackwardGlobalAveragePooling3D,
)
from jacobinet.layers.reshaping import (
    BackwardCropping1D,
    BackwardCropping2D,
    BackwardCropping3D,
    BackwardFlatten,
    BackwardPermute,
    BackwardRepeatVector,
    BackwardReshape,
    BackwardUpSampling1D,
    BackwardUpSampling2D,
    BackwardUpSampling3D,
    BackwardZeroPadding1D,
    BackwardZeroPadding2D,
    BackwardZeroPadding3D,
)

from .activations import (
    get_backward_ELU,
    get_backward_LeakyReLU,
    get_backward_PReLU,
    get_backward_ReLU,
)
from .convolutional import (
    get_backward_Conv1D,
    get_backward_Conv2D,
    get_backward_DepthwiseConv1D,
    get_backward_DepthwiseConv2D,
    get_backward_SeparableConv1D,
    get_backward_SeparableConv2D,
)
from .core import get_backward_Activation, get_backward_Dense, get_backward_EinsumDense
from .layer import (
    BackwardBoundedLinearizedLayer,
    BackwardLayer,
    BackwardLinearLayer,
    BackwardNonLinearLayer,
)
from .merging import (  # BackwardMergeNonLinearLayer,
    BackwardAdd,
    get_backward_Add,
    get_backward_Average,
    get_backward_Concatenate,
    get_backward_Maximum,
    get_backward_Minimum,
    get_backward_Multiply,
    get_backward_Subtract,
)
from .merging.base_merge import BackwardMergeNonLinearLayer

# from .custom import get_backward_MulConstant, get_backward_PlusConstant
from .normalization import get_backward_BatchNormalization
from .pooling import (
    get_backward_AveragePooling1D,
    get_backward_AveragePooling2D,
    get_backward_AveragePooling3D,
    get_backward_GlobalAveragePooling1D,
    get_backward_GlobalAveragePooling2D,
    get_backward_GlobalAveragePooling3D,
    get_backward_GlobalMaxPooling2D,
    get_backward_MaxPooling2D,
)
from .reshaping import (
    get_backward_Cropping1D,
    get_backward_Cropping2D,
    get_backward_Cropping3D,
    get_backward_Flatten,
    get_backward_Permute,
    get_backward_RepeatVector,
    get_backward_Reshape,
    get_backward_UpSampling1D,
    get_backward_UpSampling2D,
    get_backward_UpSampling3D,
    get_backward_ZeroPadding1D,
    get_backward_ZeroPadding2D,
    get_backward_ZeroPadding3D,
)
